# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Overwatch < Formula
  desc "Self-hosted monitoring server and TUI for operators"
  homepage "https://github.com/processfoundry/overwatch"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/processfoundry/overwatch/releases/download/v0.1.4/overwatch_darwin_amd64.tar.gz"
      sha256 "4ca879c84a048a6830a42ac941e5bd943be0a9f5508ccf6617f3dc0528f856f2"

      define_method(:install) do
        bin.install "overwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/processfoundry/overwatch/releases/download/v0.1.4/overwatch_darwin_arm64.tar.gz"
      sha256 "5ef227ec1efd7efefaa4ea15a7982bbaf2c83fa855526a21043b9d7a489faa68"

      define_method(:install) do
        bin.install "overwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/processfoundry/overwatch/releases/download/v0.1.4/overwatch_linux_amd64.tar.gz"
      sha256 "e39a480b8e3b52a2da04b86c9f71ba776395d4363451809d28939baa95792e56"
      define_method(:install) do
        bin.install "overwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/processfoundry/overwatch/releases/download/v0.1.4/overwatch_linux_arm64.tar.gz"
      sha256 "8d53f516f223456b5f5cc8e0e557e463e37905bdd49b18f3441b958899d1f0c6"
      define_method(:install) do
        bin.install "overwatch"
      end
    end
  end

  test do
    system "#{bin}/overwatch", "version"
  end
end
