# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Overwatch < Formula
  desc "Self-hosted monitoring server and TUI for operators"
  homepage "https://github.com/processfoundry/overwatch"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/processfoundry/overwatch/releases/download/v0.1.6/overwatch_darwin_amd64.tar.gz"
      sha256 "1f6f3428278e4c9fd9e502c967889b968a29c7b41c0129285705aa1eff29fc31"

      define_method(:install) do
        bin.install "overwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/processfoundry/overwatch/releases/download/v0.1.6/overwatch_darwin_arm64.tar.gz"
      sha256 "333800c48278b771bd65af6fa2a12f2c50070d9622fc458888d5512cd7df0980"

      define_method(:install) do
        bin.install "overwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/processfoundry/overwatch/releases/download/v0.1.6/overwatch_linux_amd64.tar.gz"
      sha256 "e4cb957777d26c1db83e22f14af117274725cebb2644791c16deec4ec6f96bef"
      define_method(:install) do
        bin.install "overwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/processfoundry/overwatch/releases/download/v0.1.6/overwatch_linux_arm64.tar.gz"
      sha256 "ee816a08b6a88cdb6720a2221eb49fefcac41b30ac879873bd95af48a6aae5b9"
      define_method(:install) do
        bin.install "overwatch"
      end
    end
  end

  test do
    system "#{bin}/overwatch", "version"
  end
end
